import { createAsyncThunk, createSlice, PayloadAction } from '@reduxjs/toolkit';
import { RootState } from '../../app/store';
import { fetchGames } from './kinoAPI';

export interface KinoState {
  games: Game[];
  status: 'idle' | 'loading' | 'failed';
}

const initialState: KinoState = {
  games: [],
  status: 'idle',
};

interface GameDate {
  d: string;
  m: string;
  year: string;
}

interface Game {
  gameNumber: string;
  gameDate: GameDate;
  bonus: number;
  drawNumbers: string[];
  game_url: string;
}

export const fetchGamesAsync = createAsyncThunk(
  'kino/fetchGames',
  async () => {
    const response = await fetchGames();
    return response.data;
  }
);

export const kinoSlice = createSlice({
  name: 'kino',
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {},
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(fetchGamesAsync.pending, (state) => {
        state.status = 'loading';
      })
      .addCase(fetchGamesAsync.fulfilled, (state, action: PayloadAction<Game[]>) => {
        state.status = 'idle';
        const gameNumbers = state.games.map(game => game.gameNumber)
        const uniqueNewGames = action.payload.filter(game => !gameNumbers.includes(game.gameNumber));
        const allGames = [...state.games, ...uniqueNewGames]
        state.games = allGames;
      })
      .addCase(fetchGamesAsync.rejected, (state) => {
        state.status = 'failed';
      });
  },
});


export const selectGames = (state: RootState) => state.kino.games;
export const selectStatus = (state: RootState) => state.kino.status;


export default kinoSlice.reducer;
